#!/usr/bin/env python3
"""Validate bindgen.sjson and expand it into the config odin-c-bindgen consumes.

Two jobs, both run by the "Generate bindings" workflow before bindgen:

validate
    odin-c-bindgen unmarshals its config with encoding/json, which ignores keys
    it does not know. A typo, or an option that never existed, is therefore
    silently dropped and the binding comes out subtly wrong. This compares every
    top-level key in bindgen.sjson against the fields of the Config struct in
    the bindgen checkout and fails on anything unknown.

expand
    Writes bindgen.generated.sjson: bindgen.sjson plus an `#any_int` override
    for every `size_t` parameter in the C API. Without it, callers must cast at
    almost every call site, because c.size_t is `uint` and `len()` gives `int`.
    There are over 200 such parameters and procedure_type_overrides takes no
    wildcards, so the list is derived from the header instead of hand-written.
    That also means parameters added upstream are covered automatically.

bindgen accepts a path to a .sjson file and uses its directory as the working
directory, so the generated config sits next to bindgen.sjson and every relative
path in it keeps working.
"""

import re
import sys

CONFIG = "bindgen.sjson"
GENERATED = "bindgen.generated.sjson"


def config_fields(bindgen_src):
    """The field names of odin-c-bindgen's Config struct."""
    src = open(f"{bindgen_src}/config.odin").read()
    body = re.search(r"Config :: struct \{(.*?)\n\}", src, re.S)
    if not body:
        sys.exit(f"error: could not find the Config struct in {bindgen_src}/config.odin")
    return set(re.findall(r"^\t(\w+)\s*:", body.group(1), re.M))


def config_keys(text):
    """Top-level keys of the sjson config. Nested entries are indented."""
    return re.findall(r"^(\w+)\s*=", text, re.M)


def validate(text, bindgen_src):
    known = config_fields(bindgen_src)
    unknown = [k for k in config_keys(text) if k not in known]
    if unknown:
        print(f"error: {CONFIG} has keys that odin-c-bindgen does not know:", file=sys.stderr)
        for k in unknown:
            print(f"  {k}", file=sys.stderr)
        print(
            "\nbindgen ignores unknown keys silently, so these do nothing.\n"
            f"Known keys: {', '.join(sorted(known))}",
            file=sys.stderr,
        )
        sys.exit(1)
    print(f"{CONFIG}: {len(config_keys(text))} keys, all known to bindgen")


def split_params(params):
    """Split a C parameter list on commas that are not inside brackets."""
    out, depth, current = [], 0, ""
    for ch in params:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(current)
            current = ""
        else:
            current += ch
    if current.strip():
        out.append(current)
    return out


def size_t_params(header):
    """(function, parameter) for every plain size_t parameter in the C API.

    Only MESHOPTIMIZER_API/EXPERIMENTAL declarations are considered, which skips
    the C++ template overloads further down the header.
    """
    src = open(header).read()
    found = []
    for m in re.finditer(
        r"MESHOPTIMIZER_(?:API|EXPERIMENTAL)\s+[\w \*]+?\s+(meshopt_\w+)\s*\((.*?)\)\s*;",
        src,
        re.S,
    ):
        fn, params = m.group(1), m.group(2)
        for p in split_params(params):
            p = p.split("=")[0].strip()          # drop any default argument
            if "*" in p or "[" in p:             # pointers are not counts
                continue
            parts = p.replace("const", "").split()
            if len(parts) == 2 and parts[0] == "size_t":
                found.append((fn, parts[1]))
    return found


def expand(text, header):
    params = size_t_params(header)
    if not params:
        sys.exit(f"error: found no size_t parameters in {header}; the parser is probably stale")

    # Never override a parameter the hand-written config already covers.
    existing = set(re.findall(r'"(meshopt_\w+\.\w+)"', text))
    entries = [(f"{fn}.{p}", "#any_int") for fn, p in params if f"{fn}.{p}" not in existing]

    block = re.search(r"^procedure_type_overrides = \{\n(.*?)^\}", text, re.S | re.M)
    if not block:
        sys.exit(f"error: {CONFIG} has no procedure_type_overrides block to extend")

    width = max(len(k) for k, _ in entries)
    lines = "".join(f'\t"{k}"{" " * (width - len(k))} = "{v}"\n' for k, v in entries)
    generated = (
        text[: block.end(1)]
        + "\n\t// Generated by scripts/prepare_bindgen.py -- do not edit here.\n"
        + lines
        + text[block.end(1) :]
    )

    with open(GENERATED, "w") as f:
        f.write(generated)
    print(f"{GENERATED}: added #any_int to {len(entries)} size_t parameters")


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: prepare_bindgen.py <bindgen-src-dir> <meshoptimizer.h>")
    bindgen_src, header = sys.argv[1], sys.argv[2]
    text = open(CONFIG).read()
    validate(text, bindgen_src)
    expand(text, header)


if __name__ == "__main__":
    main()
